#!/bin/bash

# Kill existing tmux session named 'mechsim' if it exists
tmux has-session -t mechsim 2>/dev/null
if [ $? -eq 0 ]; then
    tmux kill-session -t mechsim
fi

# Start a new kitty terminal and launch a new tmux session running 'mechsim'
kitty tmux new-session -s mechsim -n main 'mechsim -s turquoise -V 3000'
