#!/usr/bin/env bash

fzf --ansi --style=full \
  --preview 'git diff --color=always -- {} | diff-so-fancy' \
  --bind "enter:execute:git diff --color=always -- {} | less -R" \
  --header 'Select a file to view changes (Enter to open diff)' \
  --border --padding 1,1 \
  --border-label ' Git diff ' --input-label ' Search File ' \
  --color 'border:#aaaaaa,label:#cccccc' \
  --color 'preview-border:#9999cc,preview-label:#ccccff' \
  --color 'list-border:#f38ba8,list-label:#99cc99' \
  --color 'input-border:#cba6f7,input-label:#89dceb' \
  --color 'header-border:#6699cc,header-label:#99ccff'
