#!/bin/bash

PROJECT_DIR=$(
  fd --type d --max-depth 5 . ~/work ~/.config |
    fzf --style full --height=100% --border \
      --border --padding 1,1 \
      --border-label ' Tmux Session ' --input-label ' Input ' --header-label ' File Type ' \
      --preview 'tree -L 1 -C {} | head -200' \
      --preview-window=right:50% \
      --color 'border:#aaaaaa,label:#cccccc' \
      --color 'preview-border:#9999cc,preview-label:#ccccff' \
      --color 'list-border:#f38ba8,list-label:#99cc99' \
      --color 'input-border:#cba6f7,input-label:#89dceb' \
      --color 'header-border:#6699cc,header-label:#99ccff'
)
# --border-label ' Tmux Session ' --input-label ' Input ' --header-label ' File Type ' \
if [[ -z "$PROJECT_DIR" ]]; then
  exit 0
fi

SESSION_NAME=$(basename "$PROJECT_DIR" | tr '.' '_' | tr -c '[:alnum:]_' '_')

cd "$PROJECT_DIR" || exit 1

switch_to_new() {
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t "$SESSION_NAME" 1>/dev/null
  else
    tmux switch-client -t "$SESSION_NAME" 1>/dev/null
  fi
}

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  switch_to_new
else
  tmux new-session -d -s "$SESSION_NAME" -n main -c "$PROJECT_DIR"
  tmux new-window -t "$SESSION_NAME":1 -n worker1 -c "$PROJECT_DIR"
  tmux new-window -t "$SESSION_NAME":2 -n worker2 -c "$PROJECT_DIR"
  tmux new-window -t "$SESSION_NAME":3 -n logs1 -c "$PROJECT_DIR"
  tmux new-window -t "$SESSION_NAME":4 -n logs2 -c "$PROJECT_DIR"

  tmux select-window -t "$SESSION_NAME":1
  switch_to_new
fi
