#!/usr/bin/env bash

cat <<'EOF' | lolcat
          _
         | |
 _ __ ___| | ___  _ __   ___
| '__/ __| |/ _ \| '_ \ / _ \
| | | (__| | (_) | | | |  __/
|_|  \___|_|\___/|_| |_|\___|

EOF

CYAN="\e[36m"
PURPLE="\e[0;35m"
GREEN="\e[32m"
YELLOW="\e[33m"
RESET="\e[0m"

files=("atuin" "fish" "hypr" "git" "waybar" "cava" "fastfetch" "hypridle" "kitty" "mpv" "nvim" "systemd" "wakapi" "k9s" "rofi" "yazi" "starship" "dunst")

echo -e "${PURPLE}==> Syncing Obsidian Vault...${RESET}"
rclone sync -P "$HOME/Obsidian Vault" gdrive:backup/Obsidian --exclude=".git/**" && echo -e "${GREEN}✔ Obsidian Vault synced!${RESET}\n"

for dir in "${files[@]}"; do
  echo -e "${CYAN}==> Syncing ${YELLOW}${dir}${CYAN} config...${RESET}"
  rclone sync -P "$HOME/.config/$dir" "gdrive:backup/config/$dir" --exclude="Plugins/**" && echo -e "${GREEN}✔ ${dir} synced!${RESET}\n"
done

echo -e "${GREEN}==> Syncing Wallpapers...${RESET}"
rclone sync -P "$HOME/Pictures/Wallpaper" gdrive:backup/Wallpaper && echo -e "${GREEN}✔ Wallpapers synced!${RESET}\n"

echo -e "${CYAN}==> Syncing Scripts...${RESET}"
rclone sync -P "$HOME/work/main/dotsh" gdrive:backup/dotsh --exclude=".git/**" && echo -e "${GREEN}✔ Scripts synced!${RESET}\n"

echo -e "${CYAN}==> Syncing Music...${RESET}"
