#!/bin/bash


cat <<'EOF' | lolcat
  ___ __ _____  ____
 (_-</ // / _ \/ __/
/___/\_, /_//_/\__/
    /___/

EOF

CYAN="\e[36m"
GREEN="\e[32m"
YELLOW="\e[33m"
RESET="\e[0m"

hyprdots="$HOME/work/main/dotsh/sync/sync-dots"
repo="$HOME/work/main/dotsh/sync/push-dots"
cloud="$HOME/work/main/dotsh/sync/rsync"
obsidian="$HOME/work/main/dotsh/sync/sync-obsidian-vault"

notify-send -u normal -a "Sync" "🔄 Starting: Hyprdots Sync"
echo -e "${CYAN}===> Syncing Hyprdots...${RESET}"
if bash "$hyprdots"; then
    echo -e "${GREEN} ✔ Hyprdots synced successfully!${RESET}\n"
    notify-send -u normal -a "Sync" "✅ Hyprdots Sync Complete"
else
    echo -e "${YELLOW}✖ Failed to sync Hyprdots${RESET}\n"
    notify-send -u critical -a "Sync" "❌ Hyprdots Sync Failed"
fi


notify-send -u normal -a "GitHub" "🔼 Starting: Push to Hyprdots Repo"
echo -e "${CYAN}===> Pushing to ${GREEN}Hyprdots ${CYAN}on GitHub  ...${RESET}"
if bash "$repo"; then
    echo -e "${GREEN} ✔ Changes pushed to GitHub!${RESET}\n"
    notify-send -u normal -a "GitHub" "✅ Hyprdots Push Complete"
else
    echo -e "${YELLOW}✖ GitHub push failed${RESET}\n"
    notify-send -u critical -a "GitHub" "❌ Hyprdots Push Failed"
fi


notify-send -u normal -a "Cloud" "☁️ Starting: Cloud Sync"
echo -e "${CYAN}===> Syncing with Cloud...${RESET}"
if bash "$cloud"; then
    echo -e "${GREEN} ✔ Cloud sync complete!${RESET}\n"
    notify-send -u normal -a "Cloud" "✅ Cloud Sync Complete"
else
    echo -e "${YELLOW}✖ Cloud sync failed${RESET}\n"
    notify-send -u critical -a "Cloud" "❌ Cloud Sync Failed"
fi


notify-send -u normal -a "Obsidian" "🔼 Starting: Push to Obsidian Vault"
echo -e "${CYAN}===> Pushing to ${GREEN}Obsidian Vault ${CYAN}on GitHub  ...${RESET}"
if bash "$obsidian"; then
    echo -e "${GREEN} ✔ Changes pushed to GitHub!${RESET}\n"
    notify-send -u normal -a "Obsidian" "✅ Obsidian Vault Push Complete"
else
    echo -e "${YELLOW}✖ GitHub push failed${RESET}\n"
    notify-send -u critical -a "Obsidian" "❌ Obsidian Vault Push Failed"
fi
