#!/usr/bin/env bash

set -e

cat <<'EOF' | lolcat

     _____
  __|__   |__  ______  ______  ____  _____   ____  ____    ____   _
 /     \     ||      >|   ___||    ||     \ |    ||    \  |    \ | |
 |     |     ||     <  `-.`-. |    ||      \|    ||     \ |     \| |
 \_____/   __||______>|______||____||______/|____||__ \__\|__/\____|
    |_____|


EOF

OBSIDIAN_PATH="$HOME/Obsidian Vault"
cd "$OBSIDIAN_PATH" || exit

eval "$(ssh-agent -s)" >/dev/null
OUTPUT=$(ssh-add ~/.ssh/github 2>&1)

if [[ $OUTPUT =~ Identity\ added:\ .*\((.*)\) ]]; then
  EMAIL=${BASH_REMATCH[1]}
  echo -e "\e[1;32m ✔ Identity added for:\e[0m \e[1;33m$EMAIL\e[0m"
else
  echo -e "\e[1;31m✖ Failed to add identity\e[0m"
  echo -e "\e[0;90m$OUTPUT\e[0m"
fi

if git status --porcelain | grep -q " M "; then

  changes=$(
    {
      git diff --name-only
      git ls-files --others --exclude-standard
    } | cut -d'/' -f1 | sort -u
  )

  if [ -z "$changes" ]; then
    commit_msg="chore: no tracked modifications"
  else
    commit_msg="chore: $changes"
  fi

  echo $commit_msg

  echo -e "\n\e[1;36m 📦 Git status:\e[0m"
  git ss
  git add .
  git commit -m "$commit_msg"
  PUSH_OUTPUT=$(git push origin master 2>&1)

  echo -e "\n\e[1;36m$PUSH_OUTPUT\e[0m"

  echo -e "\e[1;32m ✔ Changes pushed successfully to \e[1;34morigin/$2\e[0m."

else
  echo "No changes to commit."
fi

