#!/bin/bash

fzf_preview() {
  if [ -d $1 ]; then
    echo tree
    return
  fi
  case $1 in
  *.jpg | *.jpeg | *.png | *.gif) echo 'svix -a' ;;
    # ... other cases here
  esac
}

fzf --preview='$(fzf_preview {}} {}'
